export const questions=[
    {
        title:"abc",
        desc:"jsjs",
        likes:6,
        comments:8,
        _id:123
    },
    {
        title:"def",
        desc:"jsjs",
        likes:1,
        comments:10  ,
        _id:1237
    },
    {
        title:"ermc",
        desc:"jsjs",
        likes:90,
        comments:81,
        _id:1232
    },
    {
        title:"ab11c",
        desc:"jsjs",
        likes:1,
        comments:65,
        _id:1231
    }
]
